[package]
name = "file-sync"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"]}
cloud-storage = { version = "0.11.1", features = ["global-client"] }
dotenvy = "0.15.7"
zip = "0.6.0"
futures = "0.3.31"
ini = "1.3.0"
walkdir = "2.3.3"